added solo apply (interactive) mode, ignoring pre-generated plan

diff --git a/tc b/tc
--- a/tc
+++ b/tc
@@ -25,9 +25,10 @@ FORMAT: tc <ACTION> <ALIAS> [<OPTIONS|FLAGS>] [-- any args -or --options will be
 <ALIAS>  - a unique shortcut to project/environment pair, like `runner_prod`
 
 <OPTIONS|FLAGS> - Following are available:
-    -q|--quick        - quick mode flag, skipping init and validation and format checks
-    --skip-workspace  - flag, skipping workspace selection
-    -a|--auto-approve - auto approve flag, skipping ask for approve for certain actions
+    -q|--quick        - quick mode flag, skipping init and validation and format checks [actions: plan and apply]
+    -a|--auto-approve - auto approve flag, skipping ask for approve for certain actions [actions: tf and exec]
+    --solo-apply      - run apply action in a solo mode, without pre-generated plan [actions: apply]
+    --skip-workspace  - flag, skipping workspace selection [actions: tf and exec]
 
 EOF
 
@@ -74,6 +75,7 @@ init_app() {
     # CLI params defaults
     TC_QUICK_MODE='0'
     TC_AUTO_APPROVE="$( get_sys_config '0' 'app' 'auto_approve_optional' )"
+    TC_SOLO_APPLY='0'
     TC_SKIP_WORKSPACE_SELECTION='0'
     TC_PASS_ARGS=
 }
@@ -350,6 +352,10 @@ is_quick_mode() {
     (( "${TC_QUICK_MODE}" ))
 }
 
+is_solo_apply() {
+    (( "${TC_SOLO_APPLY}" ))
+}
+
 skip_workspace_selection() {
     (( "${TC_SKIP_WORKSPACE_SELECTION}" )) && {
         echo -e "${YC} >>> ${RC}WARNING!!! ${YC} Skipping workspace selection at the alias ${YC}${TC_ALIAS} (${PROJ_DIR})${NC}."
@@ -557,16 +563,20 @@ while [[ $# -gt 0 ]]; do
   fi
   # otherwise process args
   case $key in
-    -q|--quick)         # quick mode flag, skipping init and validation and format checks
+    -q|--quick)         # quick mode flag, skipping init and validation and format checks [actions: plan and apply]
       TC_QUICK_MODE='1'
       ;;
 
-    --skip-workspace)   # flag, skipping workspace selection
-      TC_SKIP_WORKSPACE_SELECTION='1'
+    -a|--auto-approve)  # auto approve flag, skipping ask for approve for certain actions [actions: tf and exec]
+      TC_AUTO_APPROVE='1'
       ;;
 
-    -a|--auto-approve)  # auto approve flag, skipping ask for approve for certain actions
-      TC_AUTO_APPROVE='1'
+    --solo-apply)       # run apply action in a solo mode, without pre-generated plan [actions: apply]
+      TC_SOLO_APPLY='1'
+      ;;
+
+    --skip-workspace)   # flag, skipping workspace selection [actions: tf and exec]
+      TC_SKIP_WORKSPACE_SELECTION='1'
       ;;
 
     *)
@@ -627,28 +637,47 @@ case "${TC_ACTION}" in
         # TF select workspace
         select_workspace
 
-        # check TF plan
-        if [ ! -f "${TF_PLAN_FILE}" ]; then
-            echo -e "${RC}Error${NC}: TF plan file ${YC}${TF_PLAN_FILE}${NC} does not exists. \nPlease build TF plan first"
-            exit 10
+        # normal TF apply flow with pre-generated TF plan
+        if ! is_solo_apply; then
+            # check TF plan
+            if [ ! -f "${TF_PLAN_FILE}" ]; then
+                echo -e "${RC}Error${NC}: TF plan file ${YC}${TF_PLAN_FILE}${NC} does not exists. \nPlease build TF plan first"
+                exit 10
+            fi
+
+            # TF apply
+            echo -e "\n------------------------------------------------------------------------\n"
+            echo -e "${YC} >>> Applying TF plan:${NC} ${RC}${TF_PLAN_FILENAME}${NC} / alias ${YC}${TC_ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}"
+            echo -e "${YC} >>> ${NC}File ${YC}${TF_PLAN_FILE}${NC} was modified ${YC}$( get_human_time_since_file_modified "${TF_PLAN_FILE}" ) ago${NC}"
+            echo -e "\n------------------------------------------------------------------------\n"
+            
+            echo -e "This action is going to run ${YC}${TF_TOOL} apply${NC} at the ${YC}${CURRENT_WORKSPACE}${NC} workspace"
+            ask_for_approve
+
+            # apply ONLY with the pre-generated plan
+            run_docker ${TF_TOOL} apply ${TF_PLAN_FILENAME}
+            echo -e "\n${YC} >>> TF apply:${NC} alias ${YC}${TC_ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}: applied plan ${RC}${TF_PLAN_FILENAME}${NC}"
+
+            # clean-up
+            rm ${TF_PLAN_FILE}
+            echo -e "${YC} >>> ${NC}Plan ${YC}${TF_PLAN_FILE}${NC} has been ${RC}removed${NC}\n"
+
+        # solo TF apply flow, ignoring pre-generated TF plan
+        else
+            # TF apply
+            echo -e "\n------------------------------------------------------------------------\n"
+            echo -e "${YC} >>> Running TF apply in a ${NC}${RC}solo${NC}${YC} mode:${NC} / alias ${YC}${TC_ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}"
+            echo -e "${YC} >>> ${NC}Including passed arguments: ${RC}${TC_PASS_ARGS}${NC}"
+            echo -e "\n------------------------------------------------------------------------\n"
+
+            # TF tfvars
+            TFVARS_COMMAND_PARAM="$( prepare_tfvars_params )"
+
+            # apply running in solo (interactive) mode, including vars and passed arguments
+            run_docker ${TF_TOOL} apply ${TFVARS_COMMAND_PARAM} ${TC_PASS_ARGS}
+            echo -e "\n${YC} >>> TF apply:${NC} alias ${YC}${TC_ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC} / tfvars ${RC}${TFVARS_COMMAND_PARAM}${NC}"
         fi
 
-        # TF apply
-        echo -e "\n------------------------------------------------------------------------\n"
-        echo -e "${YC} >>> Applying TF plan:${NC} ${RC}${TF_PLAN_FILENAME}${NC} / alias ${YC}${TC_ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}"
-        echo -e "${YC} >>> ${NC}File ${YC}${TF_PLAN_FILE}${NC} was modified ${YC}$( get_human_time_since_file_modified "${TF_PLAN_FILE}" ) ago${NC}"
-        echo -e "\n------------------------------------------------------------------------\n"
-        
-        echo -e "This action is going to run ${YC}terreform apply${NC} at the ${YC}${CURRENT_WORKSPACE}${NC} workspace"
-        ask_for_approve
-
-        run_docker ${TF_TOOL} apply ${TF_PLAN_FILENAME}
-        # enable passed args ONLY for non-preapproved apply, when it will be done
-        # run_docker ${TF_TOOL} apply ${TF_PLAN_FILENAME} ${TC_PASS_ARGS}
-        echo -e "\n${YC} >>> TF apply:${NC} alias ${YC}${TC_ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}: applied plan ${RC}${TF_PLAN_FILENAME}${NC}"
-
-        rm ${TF_PLAN_FILE}
-        echo -e "${YC} >>> ${NC}Plan ${YC}${TF_PLAN_FILE}${NC} has been ${RC}removed${NC}\n"
         exit;;
 
     'tf')
